[package]
name = "solitaire"
version = "0.1.0"
authors = ["Mario Jim√©nez <mario_mj16@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

crossterm = "0.17"
rand = "0.7"
